#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $MARKET_DB_USER WITH PASSWORD '$MARKET_DB_PASSWORD';
    CREATE DATABASE $MARKET_DB_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $MARKET_DB_NAME TO $MARKET_DB_USER;
    ALTER DATABASE $MARKET_DB_NAME SET TIMEZONE='Europe/Amsterdam';
    \c $MARKET_DB_NAME
    ALTER SCHEMA public OWNER TO $MARKET_DB_USER;
    GRANT ALL PRIVILEGES ON SCHEMA public TO $MARKET_DB_USER;
EOSQL
