name: deploy-gateway-service

on:
  push:
    branches:
      - master
    paths:
      - gateway-service/**
      - common-domain/**

  workflow_dispatch:

jobs:

  deploy:
    runs-on: ubuntu-latest

    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      REGISTRY_UN: ${{ secrets.REGISTRY_UN }}
      REGISTRY_PW: ${{ secrets.REGISTRY_PW  }}
      NAME: gateway-service
      DIRECTORY: gateway-service
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE.
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build all modules
        run: mvn clean install -B -DskipTests

      #
      # Builds the Docker image.
      #
      - name: Build
        run: ./scripts/cd/build-image.sh
        env:
          VERSION: ${{ env.VERSION }}
          CONTAINER_REGISTRY: ${{ env.CONTAINER_REGISTRY }}
          NAME: ${{ env.NAME }}
          DIRECTORY: ${{ env.DIRECTORY }}
          REGISTRY_UN: ${{ env.REGISTRY_UN }}
          REGISTRY_PW: ${{ env.REGISTRY_PW }}

      #
      # Installs Kubectl and connects it to the cluster.
      #
      # https://github.com/marketplace/actions/kubernetes-cli-kubectl
      #
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
          kubectl-version: v1.32.2

      #
      # Expands the configuration template and deploys the microservice.
      #
      - name: Deploy
        run: ./scripts/cd/deploy.sh
        env:
          VERSION: ${{ env.VERSION }}
          CONTAINER_REGISTRY: ${{ env.CONTAINER_REGISTRY }}
          NAME: ${{ env.NAME }}