name: deploy-moviebets-ui

on:
  push: 
    branches:
      - master
    paths:
      - moviebets-ui/**

  workflow_dispatch: 

jobs:

  deploy:
    runs-on: ubuntu-latest
    
    env:
      VERSION: ${{ github.sha }}
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      REGISTRY_UN: ${{ secrets.REGISTRY_UN }}
      REGISTRY_PW: ${{ secrets.REGISTRY_PW  }}
      NAME: special
      DIRECTORY: moviebets-ui
    steps:
      
      # Checks-out your repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v3

      #
      # Builds the Docker image.
      #
      - name: Build
        run: ./scripts/cd/build-ui-image.sh
        env:
          VERSION: ${{ env.VERSION }}
          CONTAINER_REGISTRY: ${{ env.CONTAINER_REGISTRY }}
          NAME: ${{ env.NAME }}
          DIRECTORY: ${{ env.DIRECTORY }}

      #
      # Publishes the Docker image to the container registry.
      #
      - name: Publish
        run: ./scripts/cd/push-image.sh
        env:
          VERSION: ${{ env.VERSION }}
          CONTAINER_REGISTRY: ${{ env.CONTAINER_REGISTRY }}
          NAME: ${{ env.NAME }}
          REGISTRY_UN: ${{ env.REGISTRY_UN }}
          REGISTRY_PW: ${{ env.REGISTRY_PW }}

      #
      # Installs Kubectl and connects it to the cluster.
      #
      # https://github.com/marketplace/actions/kubernetes-cli-kubectl
      #
      - uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.KUBE_CONFIG }}
          kubectl-version: v1.32.2
      
      #
      # Expands the configuration template and deploys the microservice.
      #
      - name: Deploy
        run: ./scripts/cd/deploy.sh
        env:
          VERSION: ${{ env.VERSION }}
          CONTAINER_REGISTRY: ${{ env.CONTAINER_REGISTRY }}
          NAME: ${{ env.NAME }}